version: "3.9"
services:
   geant4:
      # user: $(id -u):$(id -g)
      image: "carlomt/geant4:latest-gui"
      stdin_open: true 
      tty: true
      # entrypoint: ["bash", "-l", "-c",  "geant4-config --install-datasets"]
      entrypoint: ["bash", "-l"]
      volumes:
         - ./prova:/opt/geant4/data:ro
      depends_on:
         data-downloader:
           condition: service_completed_successfully
   # 	   condition: service_healthy
   # 	 links:
   # 	   - data-downloader
   data-downloader:
      image: "carlomt/geant4:latest"
      entrypoint: ["bash", "-l", "-c",  "geant4-config --install-datasets"]
      stdin_open: true       
      tty: true      
      volumes:
         - ./prova:/opt/geant4/data
   #    healthcheck:
   #       test: ["bash", "-l", "-c",  "geant4-config --install-datasets"]
volumes:
   prova:
      external: true