ARG BASE_IMAGE=ubuntu:focal
FROM $BASE_IMAGE AS builder
LABEL maintainer="carlo.mancini-terracciano@uniroma1.it"

ARG G4_VERSION=11.1.1

#labels
LABEL org.label-schema.geant4-version=$G4_VERSION
LABEL org.label-schema.build-date=$BUILD_DATE
LABEL org.label-schema.name="carlomt/geant4"
LABEL org.label-schema.description="Geant4 Docker image with GUI"
LABEL org.label-schema.url="https://github.com/carlomt/docker-geant4"
LABEL org.label-schema.docker.cmd="docker build -t carlomt/geant4:${G4_VERSION}-gui -t carlomt/geant4:latest-gui --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --no-cache=true ."

WORKDIR /workspace

ENV LANG=C.UTF-8
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -yq --no-install-recommends install \ 
#    gnupg2 \
#    software-properties-common
     ca-certificates \
     dirmngr \
     gpg \
     wget

RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
    | gpg --dearmor - |  tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null && \
    echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] \
    https://apt.kitware.com/ubuntu/ focal main' \
    |  tee /etc/apt/sources.list.d/kitware.list >/dev/null 

COPY packages packages
COPY packages_gui packages_gui
RUN apt-get update && \
    apt-get -yq --no-install-recommends install \    
    $(cat packages) \
    $(cat packages_gui) \
    && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    rm -rf /var/cache/apt/archives/* && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /workspace/geant4/build && \
    mkdir -p /opt/geant4/ && \
    wget --quiet -O /workspace/geant4.tar.gz \
    https://geant4-data.web.cern.ch/geant4-data/releases/source/geant4-v${G4_VERSION}.tar.gz && \
    tar xf /workspace/geant4.tar.gz -C /workspace/geant4/ && \
    mv /workspace/geant4/geant4-v${G4_VERSION}/ /workspace/geant4/src/ && \
    cd /workspace/geant4/build && \
    cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/opt/geant4 \
    -DGEANT4_INSTALL_DATA=OFF \
    -DGEANT4_INSTALL_DATADIR=/opt/geant4/data \
    -DGEANT4_BUILD_MULTITHREADED=ON \
    -DGEANT4_USE_GDML=ON \
    -DGEANT4_USE_QT=ON \
    -DGEANT4_USE_OPENGL_X11=ON \
    -DGEANT4_INSTALL_EXAMPLES=OFF \
    ../src/ && \
     ninja install
    
#######################################################################

FROM $BASE_IMAGE

ENV LANG=C.UTF-8
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get -yq --no-install-recommends install \ 
#    gnupg2 \
#    software-properties-common
     ca-certificates \
     dirmngr \
     gpg \
     wget 
     
COPY packages packages
COPY packages_gui packages_gui
RUN export DEBIAN_FRONTEND=noninteractive && \
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
    | gpg --dearmor - |  tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null && \
    echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] \
    https://apt.kitware.com/ubuntu/ focal main' \
    |  tee /etc/apt/sources.list.d/kitware.list >/dev/null && \
    apt-get update && \
    apt-get -yq --no-install-recommends install \
    $(cat packages) \
    $(cat packages_gui) \    
    curl \
    && \
    rm /usr/share/keyrings/kitware-archive-keyring.gpg && \
    apt-get -yq --no-install-recommends install \
    kitware-archive-keyring \
    && \
    apt-get -y autoremove && \
    apt-get -y clean && \    
    rm -rf /var/cache/apt/archives/* && \
    rm -rf /var/lib/apt/lists/*

#RUN git clone --branch stable https://github.com/nojhan/liquidprompt.git /opt/liquidprompt

COPY --from=builder /opt/geant4/ /opt/geant4/
#COPY --from=builder /workspace/geant4/src/examples/ /opt/geant4/examples/

RUN mkdir -p /opt/geant4/data && chmod 777 /opt/geant4/data

COPY bashrc /etc/profile.d/custom.sh

ENTRYPOINT  ["/usr/bin/bash", "-l", "-c"]
